package eu.ctruillet.upssitech.sri.tp5;

public enum Action {
	ATTENTE,
	CHALUTIER_ATTAQUE,
	CHALUTIER_DEPLACE,
	CHALUTIER_SABORDE,

	DESTROYER_ATTAQUE,
	DESTROYER_DEPLACE,
	DESTROYER_SABORDE,

	SOUSMARIN_ATTAQUE,
	SOUSMARIN_DEPLACE,
	SOUSMARIN_SABORDE,
}
